sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker --version
  - docker build -t klaytonwade/store-management .
  - docker ps -a
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push klaytonwade/store-management

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
