sudo: required

language: java
jdk: oraclejdk8

services:
  - docker


script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t klaytonwade/store-management .
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push klaytonwade/store-management
